Swap out unique-string for nanoid
Turns out unique-string wasn't being compiled through babel, and `const`
keyword from crypto-random-string dependency was bubbling up and causing
errors in older browsers sans es6 support, most notably mobile Safari
(iOS) 9. Yep, Olin iPads once again...

Here's the error seen in mobile Safari console:

  SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

Probably could have stuck with unique-string and address via babel
config [1] for nuxt, but since this has evolved significantly in nuxt 2.x
and upgrading is around the corner (#79), decided it was best to just
keep it simple for now.

Issue first reported by Devin in #89.

[1] https://github.com/babel/babel/issues/9712