Bugfix: resolve JS console errors for mobile Safari 9 (iOS 9) (#118)
* Swap out unique-string for nanoid

Turns out unique-string wasn't being compiled through babel, and `const`
keyword from crypto-random-string dependency was bubbling up and causing
errors in older browsers sans es6 support, most notably mobile Safari
(iOS) 9. Yep, Olin iPads once again...

Here's the error seen in mobile Safari console:

  SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

Probably could have stuck with unique-string and address via babel
config [1] for nuxt, but since this has evolved significantly in nuxt 2.x
and upgrading is around the corner (#79), decided it was best to just
keep it simple for now.

Issue first reported by Devin in #89.

[1] https://github.com/babel/babel/issues/9712

* Add source-map-loader as dependency

To address the 404 on mobile Safari 9 (iOS 9) for /.nuxt/es6-promise.map

This is a source map from nuxt dependency of es6-promise [1]. The 404 did
not appear to have any adverse effect of consequence on the app, so not
convinced this change is necessary. But figured it was worth cleaning up
the console while debugging for `const` keyword error addressed in
previous commit (4bb1ad0).

[1] https://github.com/stefanpenner/es6-promise/issues/235#issuecomment-406761142